source 'https://rubygems.org'

ruby '2.2.3'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rspec-sinatra'
gem 'capybara'
gem 'rspec'
gem 'database_cleaner'
gem 'rake'
gem 'sinatra-flash'
gem 'byebug'
gem 'bcrypt'
gem 'rack'
